version: '2'

networks:
  vocab_network:
    #external:
    #  name: nginxproxynetwork
    external: false

volumes:
  vocab_es:

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
    volumes:
    #  - vocab_es:/usr/share/elasticsearch/data
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - vocab_network

  kibana:
      image: docker.elastic.co/kibana/kibana:7.5.2
      environment:
        ELASTICSEARCH_URL: http://elastic:9200
        ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'    
      ports:
        - 5601:5601 
      networks:
        - vocab_network         

  backend:
    build:
       context: ./
       #dockerfile: Dockerfile.backend.dev
       dockerfile: Dockerfile.backend
    environment:
       - VIRTUAL_HOST=vocab-service.sd.di.huc.knaw.nl
    ports:
       - 5050:5000
    volumes:
       - ./data:/data
       #- ./backend/src:/usr/src/app
    networks:
       - vocab_network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    restart: always
    environment:
      - VIRTUAL_HOST=vocab.sd.di.huc.knaw.nl
    ports:
      - 80:80
    networks:
      - vocab_network