version: '2'

networks:
  vocab_network:
    #external:
    #  name: nginxproxynetwork
    external: false

volumes:
  vocab_es:

services:

  elastic:
    image: arm64v8/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
    #  - vocab_es:/usr/share/elasticsearch/data
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - vocab_network

  kibana:
      image: arm64v8/kibana:8.10.2
      environment:
        ELASTICSEARCH_URL: http://elastic:9200
        ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
      ports:
        - 5601:5601
      networks:
        - vocab_network

  app:
    build:
       context: ./
       #dockerfile: Dockerfile.dev
       dockerfile: Dockerfile
    environment:
      - ES_HOST=elastic
      - RECORDS_PATH=/data/records/
      - DOCS_PATH=/data/docs/

    ports:
       - 5001:5000
    volumes:
       - ./data:/data
       #- ./backend/src:/usr/src/app
    networks:
       - vocab_network