version: '2'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
